config/routes.rb
Rails.application.routes.draw do
  resources :facilities do
    member do
      post :create_doctor
    end
    resources :patients do
      member do
        patch :deactivated_patient
        patch :wait_patient
        patch :check_patient
        patch :xray_patient
        patch :surgery_patient
        patch :pay_patient
        patch :leave_patient
        post :create_doctor
      end
    end
  end  
  resources :meds
  
  
 
 

  root 'home#index'

end

app/models/med.rb
class Med < ActiveRecord::Base
  has_many :patient_meds
  has_many :patients, through: :patient_meds


  MED_OPTIONS = [
    "Accupril",
    # highblood pressure
    "Acetaminophen",
    # pain reliever analgesics (pain relievers) 
    # and antipyretics (fever reducers)
    "Ambien",
    # insomnia, sedative
    "Mefoxin",
    #antibiotic injection/IV
    "Mycelex",
    #anti fungal cream
    "Zanaflex",
    # skeletal muscle relaxer, MS
    "Zyrtec",
    # antihistimine, allergy
    "Sonata",
    # insomnia
    "Stadol",
    #painkiller,
    "Kineret",
    #pain reliever, arthiritis
    "Penicillin",
    #antibiotic
    "Ibuprofen",
    # pain reliever, reduce swelling
  ]
end

app/controllers/meds_controller.rb
class MedsController < ApplicationController
  require 'enumerator'

  def index
    @meds = if !params[:q].blank?
    Med.where("name LIKE ? OR dose LIKE ? OR description LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
    Med.all
    end
    @meds = Med.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @meds = Med.new 
    @patients = Patient.all
  end

  def create
    @meds = Med.create med_params
    @patients = Patient.all
    if @med.save 
      flash[:notice] = 'Medication Record Created'
      redirect_to meds_path
    else 
      flash[:error] = 'No Record Created' 
      render :new
    end
  end

  def edit
    @meds = Med.find params[:id]
  end

  def update
    @med = Med.find params[:id]
    @med.update(med_params)
    if @med.save
      flash[:notice] = 'Medication Record Updated'
      redirect_to meds_path
    else 
      flash[:error] = 'Update Not Saved'
      render :edit
    end
  end

  def destroy
    @med = Med.find params[:id]
    @med.destroy
    redirect_to meds_path
  end

private 
  def med_params
    params.require(:med).permit(
  :name,
  :dose,
  :description,
  patient_ids: []
  )
  end

end

app/helpers/meds_helper.rb
module MedsHelper
end

app/views/meds/_form.html.haml
= form_for [@meds] do |f|
  .form-group
  = f.label :name
  = f.text_field :name, class: "name-field validate-test"
  %br/
  = f.label :dose
  = f.text_field :dose
  %br/
  = f.label :description
  = f.text_field :description
  %br/
  = f.submit "Submit", class: 'btn btn-primary disabled submit-info'
  / class: "btn btn-primary disabled submit-info"

app/views/meds/edit.html.haml
%h3 Edit Info

= render 'form' 

app/views/meds/index.html.haml
%h3 Medications

= link_to 'Facility Home', facilities_path
%br/
= form_tag meds_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    =text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default
        %i.glyphicon.glyphicon-search

= link_to 'Add Med', new_med_path

.container-fluid
  .row
  - x = 0
  - y = 1
  %ul.list-unstyled{class: "property_list"}
    - @meds.each_slice(10) do |row|
      %li{class: "section_#{x+1}"}
      - x = x+1
      - row.each do |med|
        .col-md-3
          .list-group-item
            = med.name
            = link_to 'View', meds_path
            = link_to 'Edit', edit_med_path(med)
            = link_to 'Delete', med_path(med), method: :delete
          %br/
.col-md-12.text-center
  %ul{class: "link_list"}
    - x.times do
      %li{class: "link_#{y}"}
        %a{class: "link_#{y}", med_num: y}
          ="page #{y}"
      - y += 1
%br/



    

app/views/meds/new.html.haml
%h3 Enter Med information
<br>
= render 'form' 

app/views/meds/show.html.haml
%h2 Content