config/routes.rb
Rails.application.routes.draw do
  resources :facilities do
    member do
      post :create_doctor
    end
    resources :patients do
      member do
        patch :deactivated_patient
        patch :wait_patient
        patch :check_patient
        patch :xray_patient
        patch :surgery_patient
        patch :pay_patient
        patch :leave_patient
        post :create_doctor
      end
    end
  end  
  resources :meds
  
  
 
 

  root 'home#index'

end

app/models/facility.rb
class Facility < ActiveRecord::Base
  has_many :patients, dependent: :destroy
  has_many :meds
  has_many :doctors, as: :doctorable

  SPECIALTIES = [
    "Allergy",
    "Oncology",
    "Endocronologist",
    "Emergeny",
    "Intensive Care",
    "Podiatry",
    "Geriatrics",
    "Surgery"
  ]
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  require 'enumerator'
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  def index
    @facilities = if !params[:q].blank?
    Facility.where("name LIKE ? OR address LIKE ? OR zip LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
    Facility.all
    end
    @facilities = Facility.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.create fac_params
    if @facility.save
      flash[:notice] = 'Facility Created'
      redirect_to facilities_path
    else 
      flash[:error] = 'No Record Created' 
      render :new
    end 
  end

  def create_doctor
    @facility = Facility.find params[:id]
    @doctor = @facility.doctors.create doctor_params
    if @doctor.save
      flash[:notice] = 'Doctor Record Created'
      redirect_to facility_path(@facility)
    else
      flash[:error] = 'No Record Created'
      redirect_to facilities_path
    end
  end
  
  def edit
  end

  def update
    @facility.update(fac_params)
    if @facility.save
      flash[:notice] = 'Facility Updated'
      redirect_to @facility
    else
      flash[:error] = 'Updates not saved'
      render :edit
    end
  end

  def destroy
    @facility.destroy
    redirect_to facilities_path
  end

  def show
    @facility = Facility.find params[:id]
    @patients = @facility.patients
    @doctor = Doctor.new
    @doctors = @facility.doctors
  end


  private

  def doctor_params
    params.require(:doctor).permit(
      :name,
      :specialty
    )
  end
  
  def set_facility
    @facility = Facility.find(params[:id])
  end
  
  def fac_params 
    params.require(:facility).permit(
      :name,
      :address,
      :zip,
      :specialty
    )
  end

end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.haml
= form_for @facility do |f|
  -if @facility.errors.any?
    %p#notice= notice
    -@facility.errors.full_messages.each do |message|
      =message



= form_for @facility do |f|
  .form-group
  = f.label :name
  = f.text_field :name, class: "validate-test"
  %p.error-message Name Required
  %br/
  .form-group
  = f.label :address
  = f.text_field :address
  %br/
  .form-group
  = f.label :zip
  = f.text_field :zip
  %br/
  .form-group
  = f.label :specialty
  = f.text_field :specialty

  = f.submit "Submit", class: "btn btn-primary disabled submit-info"

app/views/facilities/edit.html.haml
%h2 Edit Facility Information

= render 'form'

app/views/facilities/index.html.haml
%h1 Regional Hospital Diretory

= form_tag facilities_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default
        %i.glyphicon.glyphicon-search
= link_to "Create New Facility", new_facility_path 


.container
  .row
    %ul.list-unstyled 
      -@facilities.each do |facility|   
        %li
        = facility.name 
        = link_to "Edit", edit_facility_path(facility)  
        = link_to "Delete", facility_path(facility), method: :delete 
        = link_to "View", facility_path(facility)  


= will_paginate @facilities 
/   .row
/   - x = 0
/   - y = 1
/   %ul{class: "property_list"}
/     - @facilities.each_slice(10) do |row|
/       %li{class: "section_#{x+1}"}
/       - x = x+1
/       - row.each do |facility|
/         .col-md-3
/           .list-group-item  
/             = facility.name 
/             = link_to "Edit", edit_facility_path(facility)
/             = link_to "Delete", facility_path(facility), method: :delete 
/             = link_to "View", facility_path(facility)  
/ .col-md-12.text-center
/   %ul{class: "link_list"}
/     - x.times do
/       %li{class: "link_#{y}"}
/         %a{class: "link_#{y}", med_num: y}
/           ="page #{y}"
/       - y += 1

app/views/facilities/new.html.haml
%h2 Create New Facility

= render 'form' 

app/views/facilities/show.html.haml
%h4 Hospital Information
= @facility.name
%br
= @facility.address
= @facility.zip
%br
= link_to "Patient Records", facility_patients_path(@facility)
= link_to "Medications", meds_path


%p
%h5 Physicians/Specialties
%ul.list-unstyled
  -@facility.doctors.each do |doctor|
    %li
      = "Dr."    
      = doctor.name
      = "-"
      = doctor.specialty

= form_for @doctor, url: create_doctor_facility_path(@facility) do |f|
  = f.label :name
  = f.text_field :name, class: "validate-test"
  %br/
  = f.label :specialty
  = f.text_field :specialty
  %br/
  = f.submit

= link_to "Back to Facility Directory", facilities_path