config/routes.rb
Rails.application.routes.draw do
  resources :facilities do
    member do
      post :create_doctor
    end
    resources :patients do
      member do
        patch :deactivated_patient
        patch :wait_patient
        patch :check_patient
        patch :xray_patient
        patch :surgery_patient
        patch :pay_patient
        patch :leave_patient
        post :create_doctor
      end
    end
  end  
  resources :meds
  
  
 
 

  root 'home#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base

has_many :patient_meds
has_many :meds, through: :patient_meds
has_many :doctors, as: :doctorable
belongs_to :facility

B_T_OPTIONS = [
  "A-",
  "A+",
  "B-",
  "B+",
  "AB-",
  "AB+",
  "O-",
  "O+"
]


validates :first_name, presence:true
validates :last_name, presence:true

validates :gender, presence:true
validates :blood_type, presence:true
validate :age_10_or_older

  def age_10_or_older
    if self.d_o_b
    errors.add(:d_o_b, 'You must be over 10 years of age.') if self.d_o_b > 10.years.ago.to_date.to_s
    end
  end

include Workflow
workflow do

  state :deactivated do
    event :wait, transition_to: :waiting
  end

  state :waiting do
    event :check, transition_to: :checked
    event :xray, transition_to: :xrayed
    event :surgery, transition_to: :surgeryed
    event :leave, transition_to: :leaving
  end

  state :checked do
    event :wait, transition_to: :waiting
    event :xray, transition_to: :xrayed
    event :surgery, transition_to: :surgeryed
    event :pay, transition_to: :paying
  end

  state :xrayed do
    event :wait, transition_to: :waiting
    event :check, transition_to: :checked
    event :surgery, transition_to: :surgeryed
    event :pay, transition_to: :paying
  end 

  state :surgeryed do
    event :wait, transition_to: :waiting
    event :check, transition_to: :checked
    event :xray, transition_to: :xrayed
    event :pay, transition_to: :paying
  end

  state :paying do
    event :leave, transition_to: :leaving
  end

  state :leaving do
    event :deactivate, transition_to: :deactivated
  end
end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
 require 'enumerator'
  
  before_action :set_patient, only: [
    :show,
    :edit,
    :update,
    :destroy,
    :wait_patient,
    :check_patient,
    :xray_patient,
    :surgery_patient,
    :pay_patient,
    :leave_patient,
    :deactivate_patient,
  ]
  def index
    if params[:facility_id]
    @facility = Facility.find params[:facility_id]
    @patients = @facility.patients
  elsif !params[:q].blank?
    @patients = Patient.where("first_name LIKE ? OR last_name LIKE ? OR d_o_b LIKE ? OR description LIKE ? OR gender LIKE ? OR blood_type LIKE ?", "%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%")
    @searchentry = "Search results for: #{params[:q]}"
    else
    Patient.all 
    end
  @patients = Patient.paginate(:page => params[:page], :per_page => 10)
  end

  def search_results
    Patient.where("first_name LIKE ? OR last_name LIKE ? OR d_o_b LIKE ? OR description LIKE ? OR gender LIKE ? OR blood_type LIKE ?", "%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%")
    p @patients
    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @facility = Facility.find params[:facility_id]
    @patient = @facility.patients.new
    @meds = Med.all
  end

  def create 
    @facility = Facility.find params[:facility_id]
    @patient = @facility.patients.create pat_params
    @meds = Med.all
    if @patient.save
      flash[:notice] = 'Patient Record Created'
      redirect_to facility_patients_path
    else
      flash[:error] = 'No Record Created'
      render :new
    end
  end

  def edit
    @patients = Patient.find params[:id]
    @facility = Facility.find params[:facility_id]
    @meds = Med.all
  end

  def update
    @patient.update_attributes pat_params 
    if @patient.save  
      flash[:notice] = 'Patient Record Update'
    else
      flash[:error] = 'Update Incomplete'
    end
  redirect_to facility_patients_path 
  end

  def show
    @patients = Patient.all
    @facility = Facility.find params[:facility_id]
    @patient = Patient.find params[:id]
    @meds = @patient.meds
    @doctor = Doctor.new
    @doctors = @patient.doctors
  end

  def create_doctor
    @patient = Patient.find params[:id]
    @doctor = @patient.doctors.create doctor_params
    redirect_to facility_patients_path(@facility)
  end

  def destroy
    @facility = Facility.find params[:facility_id]
    @patient = Patient.find params[:id]
    @patient.destroy
    redirect_to facility_patients_path(@facility)
  end

  def deactivated_patient 
    @facility = Facility.find params[:facility_id]
    set_patient
    @patient.deactivate!
    respond_to do |format|
      format.js
    end   
  end 

  def wait_patient
    @facility = Facility.find params[:facility_id]
    set_patient
    @patient.wait!
    redirect_to facility_patients_path
    
  end

  def check_patient
    @facility = Facility.find params[:facility_id]    
    set_patient
    @patient.check!
    redirect_to facility_patients_path
  end

  def xray_patient
    set_patient
    @patient.xray!
    redirect_to facility_patients_path
  end

  def surgery_patient
    set_patient
    @patient.surgery!
    redirect_to facility_patients_path
  end

  def pay_patient
    set_patient
    @patient.pay!
    redirect_to facility_patients_path
  end

  def leave_patient
    set_patient
    @patient.leave!
    redirect_to facility_patients_path
  end

private

  def set_patient
    @patient = Patient.find params[:id]
  end
  
  def doctor_params
    params.require(:doctor).permit(
      :name,
      :specialty
      )
  end

  def find_patient
    @patient = Patient.find params[:id]
  end 

  def pat_params
    params.require(:patient).permit(
      :first_name,
      :last_name,
      :d_o_b,
      :description,
      :gender,
      :blood_type, 
      med_ids: [],
      patient_ids: []
      )
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
= form_for([@facility,@patient]) do |f| 
  - if @patient.errors.any? 
    %p#notice= notice
    -@patient.errors.full_messages.each do |message| 
      =message
    
= form_for([@facility,@patient]) do |f| 
  .form-group
    =f.label :first_name 
    = f.text_field :first_name
  %br/
  .form-group
  =f.label :last_name 
  = f.text_field :last_name, class: "validate-test"
  %p.error-message Last Name Required
  %br/ 
  .form-group 
  =f.label :date_of_birth 
  = f.date_field :d_o_b
  %br/ 
  .form-group 
  =f.label :description 
  =f.text_area :description
  %br/
  .form-group
  %fieldset
  =f.label :gender 
  Male
  =f.radio_button :gender, "Male"
  Female
  =f.radio_button :gender, "Female"
  %br/
  .form-group
  =f.label :blood_type 
  =f.select :blood_type, options_for_select(Patient::B_T_OPTIONS, f.object.blood_type), include_blank: "---select---"  
  %br/
  .field
  =hidden_field_tag 'patient[med_ids][]',''
  - @meds.each do |med|
    =check_box_tag 'patient[med_ids][]', med.id,@patient.meds.include?(med)
    = med.name
  
  = f.submit "Submit", class: "btn btn-primary submit-info"

app/views/patients/_index.html.haml
%h3 Patient Records


=link_to "Home", facilities_path(@facility)
=link_to 'New Patient', new_facility_patient_path


%body
= form_tag facility_patients_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default
        %i.glyphicon.glyphicon-search

%ul
- @patients.each do |patient| 
  %li  
  =patient.first_name 
  =patient.last_name 
  =link_to 'View Patient Info', facility_patient_path(@facility,patient)


  

app/views/patients/_workflow.html.haml
= patient.workflow_state
- facility = @patient.facility

-if patient.deactivated?
  = link_to "Patient Waiting", 'javascript:void(0);', class: "update-wait", patient_id: @patient

-if patient.waiting?
  = link_to "Check Up", 'javascript:void(0):', class: "update-check"
  = link_to "X-ray", 'javascript:void(0):', class: "update-xray", facility_id: @facility
  = link_to "Surgery", 'javascript:void(0):', class: "update-surgery", facility_id: @facility
  = link_to "Leave", 'javascript:void(0):', class: "update-leave", facility_id: @facility



 

app/views/patients/check_patient.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'workflow', patient: @patient)}");

app/views/patients/deactivated_patient.js.haml
$(".workflow).html("#{j(render 'workflow', patient: @patient)}");

app/views/patients/edit.html.haml
%h2 Edit Patient Record

= render "form" 

app/views/patients/index.html.haml
%h3 Patient Records


=link_to "Facility Home", facility_path(@facility)
=link_to 'New Patient', new_facility_patient_path


%body
= form_tag facility_patients_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default
        %i.glyphicon.glyphicon-search


.container
 
  %ul.list-unstyled
    -@patients.each do |patient| 
      %li
      = patient.last_name
      = patient.first_name 
      = link_to "Edit", edit_facility_patient_path(@facility, patient)  
      = link_to "Delete", facility_patient_path(@facility, patient), method: :delete 
      = link_to "View", facility_patient_path(@facility, patient)  


= will_paginate @facilities 



  

app/views/patients/new.html.haml
%h3 Enter Patient Information

=render 'form'

app/views/patients/search_results.js.haml
$("").html("#{j(render'index')}")

app/views/patients/show.html.haml
%html
  
  %h3 Patient Information
  
  %body
  .container
  = @patient.first_name 
  = @patient.last_name 
  = @patient.d_o_b 
  = @patient.description 
  = @patient.gender
  = @patient.blood_type
  .workflow{class: ".workflow"}
    = render 'workflow', patient: @patient
  %br/  
  
  = link_to "Back", facility_patients_path(@facility) 
  = link_to "Edit", edit_facility_patient_path(@facility,@patient)
  = link_to "Delete Record", facility_patient_path(@facility,@patient), method: :delete

  %ul
    -@meds.each do |med| 
      %li
      = med.name 
      = med.dose 
      = med.description  

- @patient.doctors.each do |doctor|
  %li
    = doctor.name
    = doctor.specialty
= form_for @doctor, url: create_doctor_facility_patient_path(@facility,@patient) do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :specialty
  = f.text_field :specialty
  %br/
  = f.submit

app/views/patients/wait_patient.js.haml
$(".workflow").html("#{j(render 'workflow', patient: @patient)}");